---
services:
  - docker

env:
  global:
    - ROLE_NAME: authselect
    - AUTHOR_NAME: smlloyd

addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

install:
  # Install ansible and molecule
  - pip3 install ansible-lint molecule molecule-docker docker

before_script:
  # Use galaxy role name
  - cd ../
  - mv ansible-role-$ROLE_NAME $AUTHOR_NAME.$ROLE_NAME
  - cd $AUTHOR_NAME.$ROLE_NAME

script:
  - molecule test --scenario-name travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
